runtime:
  container_commands:
  - apt-get update
  - apt-get install -y git
  python:
    version: '3.10'
    requirements:
    - pipeline-ai
    - torch
    - numpy
accelerators: ["nvidia_t4"]
accelerator_memory: 16000
pipeline_graph: new_pipeline:my_new_pipeline
pipeline_name: hello-torch
description: null
readme: README.md
extras: {}
cluster: null
